### ISSUE TITLE
too much in stderr

### ISSUE THREAD

**Issue by byb121** [dockstore/s3cmd-plugin#1]
Hi,

I found when it's uploading results to s3, it also outputs meta data of my s3 bucket to stderr (for each uploading!!), which is a lot (400K characters for me, as I have too many files in the bucket). it's a minor issue and can be easily handled, but I'm not sure what's the use of it and I'd like it not to output metadata in anyway.

By metadata I meant info like policy, name, file keys, owners, sizes etc of the bucket, example is below.

Thanks,
Yaobo

Example output (only a tiny part of the whole output):
```
Calling on plugin io.dockstore.provision.S3CmdPlugin$S3CmdProvision to provision from /home/ubuntu/./datastore/launcher-63d9b673-c49d-4a44-8d9c-989ee230a241/outputs/f3e5b32e-3698-11e7-90d5-7b4f8b6ca8b2.bam.bas to s3cmd://team78-pan-prostate/test_small_sample/test_output/f3e5b32e-3698-11e7-90d5-7b4f8b6ca8b2/cgpmap-results/f3e5b32e-3698-11e7-90d5-7b4f8b6ca8b2.cgpmap.bam.bas

   policy:    <?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>team78-pan-prostate</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>true</IsTruncated><Contents><Key>ref/human/CNV_SV_ref_GRCh37d5.tar.gz</Key><LastModified>2017-03-30T13:14:55.925Z</LastModified><ETag>&quot;2473765faca7a9c2293c8195f95a3709-45&quot;</ETag><Size>2973713561</Size><StorageClass>STANDARD</StorageClass><Owner><ID>panprostate</ID><DisplayName>Panprostate (contact kr2 if necessary)</DisplayName></Owner></Contents><Contents><Key>ref/human/SNV_INDEL_ref_GRCh37d5.tar.gz</Key><LastModified>2017-03-30T13:15:49.970Z</LastModified>
```

**Comment by denis-yuen** [comment]
@garyluu worth a look, at first glance the xml doesn't look like Java logging output though

**Comment by garyluu** [comment]
That's actually stdout coming from the check bucket function/command.  I'll be removing that stdout since it's not very relevant to the upload/download command.

**Comment by garyluu** [comment]
And it's done https://artifacts.oicr.on.ca/artifactory/collab-release/io/dockstore/dockstore-file-s3cmd-plugin/0.0.5/dockstore-file-s3cmd-plugin-0.0.5.zip
