### ISSUE TITLE
Location of s3cmd binary is assumed

### ISSUE THREAD

**Issue by keiranmraine** [dockstore/s3cmd-plugin#4]
The plugin expects the s3cmd binary at `/usr/bin/s3cmd`.  Could it try to discover via `which` instead?

Working round by using symlinks for now.

**Comment by denis-yuen** [comment]
@keiranmraine  can this be configured using the client key at https://github.com/dockstore/s3cmd-plugin#configuration ?

**Comment by keiranmraine** [comment]
Sorry, yes.  Host startup script had a legacy config predating use of the s3 plugin.
